repoRoot = fileparts(fileparts(mfilename('fullpath')));
modelDir = fullfile(repoRoot, 'models', 'simulink');
shotDir = fullfile(repoRoot, 'assets', 'screenshots');

if ~exist(modelDir, 'dir')
    mkdir(modelDir);
end

if ~exist(shotDir, 'dir')
    mkdir(shotDir);
end

modelName = 'buck_discrete_pi_voltage_loop';
modelPath = fullfile(modelDir, [modelName '.slx']);
shotPath = fullfile(shotDir, '04-simulink-discrete-pi-control.png');

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist(modelPath, 'file')
    delete(modelPath);
end

new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'Solver', 'ode4', ...
    'FixedStep', '2.5e-7', ...
    'StopTime', '0.012', ...
    'SimulationMode', 'normal');

add_block('simulink/Sources/Constant', [modelName '/Vref 12V'], ...
    'Position', [60 115 130 145], ...
    'Value', '12');

add_block('simulink/Sources/Step', [modelName '/Vin step 24V to 20V'], ...
    'Position', [520 255 675 295], ...
    'Time', '0.003', ...
    'Before', '24', ...
    'After', '20');

add_block('simulink/Sources/Step', [modelName '/Rload step 2.4ohm to 1.6ohm'], ...
    'Position', [480 365 675 405], ...
    'Time', '0.007', ...
    'Before', '2.4', ...
    'After', '1.6');

add_block('simulink/Ports & Subsystems/Subsystem', [modelName '/Discrete PI voltage controller'], ...
    'Position', [300 80 540 220]);
build_controller_subsystem([modelName '/Discrete PI voltage controller']);

add_block('simulink/Ports & Subsystems/Subsystem', [modelName '/Averaged Buck plant'], ...
    'Position', [735 200 985 415]);
build_plant_subsystem([modelName '/Averaged Buck plant']);

add_block('simulink/Signal Routing/Mux', [modelName '/Scope mux'], ...
    'Position', [1320 120 1350 320], ...
    'Inputs', '6');

add_block('simulink/Sinks/Scope', [modelName '/Scope Vout duty error'], ...
    'Position', [1415 190 1515 280], ...
    'NumInputPorts', '1');

add_block('simulink/Signal Routing/From', [modelName '/from Vout feedback'], ...
    'Position', [190 165 260 195], ...
    'GotoTag', 'Vout_fb');

add_block('simulink/Signal Routing/Goto', [modelName '/goto Vout feedback'], ...
    'Position', [1030 210 1110 240], ...
    'GotoTag', 'Vout_fb');

add_block('simulink/Signal Routing/Goto', [modelName '/goto duty monitor'], ...
    'Position', [600 95 665 125], ...
    'GotoTag', 'duty_cmd');

add_block('simulink/Signal Routing/Goto', [modelName '/goto error monitor'], ...
    'Position', [600 145 665 175], ...
    'GotoTag', 'pi_error');

add_block('simulink/Signal Routing/Goto', [modelName '/goto integrator monitor'], ...
    'Position', [600 195 665 225], ...
    'GotoTag', 'pi_xI');

add_block('simulink/Signal Routing/Goto', [modelName '/goto IL monitor'], ...
    'Position', [1030 275 1110 305], ...
    'GotoTag', 'IL_avg');

add_block('simulink/Signal Routing/Goto', [modelName '/goto Iout monitor'], ...
    'Position', [1030 355 1110 385], ...
    'GotoTag', 'Iout_avg');

add_monitor_from(modelName, 'mon Vout', 'Vout_fb', [1210 115 1285 145], 1);
add_monitor_from(modelName, 'mon duty', 'duty_cmd', [1210 150 1285 180], 2);
add_monitor_from(modelName, 'mon error', 'pi_error', [1210 185 1285 215], 3);
add_monitor_from(modelName, 'mon xI', 'pi_xI', [1210 220 1285 250], 4);
add_monitor_from(modelName, 'mon IL', 'IL_avg', [1210 255 1285 285], 5);
add_monitor_from(modelName, 'mon Iout', 'Iout_avg', [1210 290 1285 320], 6);

add_line(modelName, 'Vref 12V/1', 'Discrete PI voltage controller/1', 'autorouting', 'on');
add_line(modelName, 'from Vout feedback/1', 'Discrete PI voltage controller/2', 'autorouting', 'on');
add_line(modelName, 'Discrete PI voltage controller/1', 'Averaged Buck plant/2', 'autorouting', 'on');
add_line(modelName, 'Vin step 24V to 20V/1', 'Averaged Buck plant/1', 'autorouting', 'on');
add_line(modelName, 'Rload step 2.4ohm to 1.6ohm/1', 'Averaged Buck plant/3', 'autorouting', 'on');

add_line(modelName, 'Discrete PI voltage controller/1', 'goto duty monitor/1', 'autorouting', 'on');
add_line(modelName, 'Discrete PI voltage controller/2', 'goto error monitor/1', 'autorouting', 'on');
add_line(modelName, 'Discrete PI voltage controller/3', 'goto integrator monitor/1', 'autorouting', 'on');
add_line(modelName, 'Averaged Buck plant/1', 'goto Vout feedback/1', 'autorouting', 'on');
add_line(modelName, 'Averaged Buck plant/2', 'goto IL monitor/1', 'autorouting', 'on');
add_line(modelName, 'Averaged Buck plant/3', 'goto Iout monitor/1', 'autorouting', 'on');
add_line(modelName, 'Scope mux/1', 'Scope Vout duty error/1', 'autorouting', 'on');
save_system(modelName, modelPath);
set_param(modelName, 'ZoomFactor', 'FitSystem');
print(['-s' modelName], '-dpng', '-r180', shotPath);
close_system(modelName, 0);

fprintf('已生成 Simulink 离散 PI 控制框图: %s\n', shotPath);
fprintf('已保存 Simulink 模型: %s\n', modelPath);

function add_monitor_from(modelName, blockName, tagName, position, muxPort)
    add_block('simulink/Signal Routing/From', [modelName '/' blockName], ...
        'Position', position, ...
        'GotoTag', tagName);
    add_line(modelName, [blockName '/1'], ['Scope mux/' num2str(muxPort)], 'autorouting', 'on');
end

function build_controller_subsystem(sys)
    open_system(sys);
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']);
    delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/Vref'], ...
        'Position', [45 75 75 95]);
    add_block('simulink/Sources/In1', [sys '/Vout'], ...
        'Position', [45 150 75 170]);
    add_block('simulink/Math Operations/Sum', [sys '/e = Vref - Vout'], ...
        'Position', [125 95 160 135], ...
        'Inputs', '+-');
    add_block('simulink/Commonly Used Blocks/Gain', [sys '/Kp = 0.05'], ...
        'Position', [215 60 305 100], ...
        'Gain', '0.05');
    add_block('simulink/Discrete/Discrete-Time Integrator', [sys '/Ki accumulator'], ...
        'Position', [215 130 315 180], ...
        'gainval', '200', ...
        'SampleTime', '5e-6', ...
        'InitialCondition', '0.0041667');
    add_block('simulink/Sources/Constant', [sys '/Dff = 0.5'], ...
        'Position', [215 225 295 255], ...
        'Value', '0.5');
    add_block('simulink/Math Operations/Sum', [sys '/duty = Dff + P + I'], ...
        'Position', [380 115 420 175], ...
        'Inputs', '+++');
    add_block('simulink/Discrete/Zero-Order Hold', [sys '/PWM update Ts=5us'], ...
        'Position', [475 125 595 165], ...
        'SampleTime', '5e-6');
    add_block('simulink/Sinks/Out1', [sys '/duty'], ...
        'Position', [660 130 690 150]);
    add_block('simulink/Sinks/Out1', [sys '/error'], ...
        'Position', [660 205 690 225]);
    add_block('simulink/Sinks/Out1', [sys '/xI'], ...
        'Position', [660 265 690 285]);

    add_line(sys, 'Vref/1', 'e = Vref - Vout/1', 'autorouting', 'on');
    add_line(sys, 'Vout/1', 'e = Vref - Vout/2', 'autorouting', 'on');
    add_line(sys, 'e = Vref - Vout/1', 'Kp = 0.05/1', 'autorouting', 'on');
    add_line(sys, 'e = Vref - Vout/1', 'Ki accumulator/1', 'autorouting', 'on');
    add_line(sys, 'Kp = 0.05/1', 'duty = Dff + P + I/1', 'autorouting', 'on');
    add_line(sys, 'Ki accumulator/1', 'duty = Dff + P + I/2', 'autorouting', 'on');
    add_line(sys, 'Dff = 0.5/1', 'duty = Dff + P + I/3', 'autorouting', 'on');
    add_line(sys, 'duty = Dff + P + I/1', 'PWM update Ts=5us/1', 'autorouting', 'on');
    add_line(sys, 'PWM update Ts=5us/1', 'duty/1', 'autorouting', 'on');
    add_line(sys, 'e = Vref - Vout/1', 'error/1', 'autorouting', 'on');
    add_line(sys, 'Ki accumulator/1', 'xI/1', 'autorouting', 'on');

    Simulink.BlockDiagram.arrangeSystem(sys);
    close_system(sys);
end

function build_plant_subsystem(sys)
    open_system(sys);
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']);
    delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/Vin'], ...
        'Position', [45 65 75 85]);
    add_block('simulink/Sources/In1', [sys '/duty'], ...
        'Position', [45 125 75 145]);
    add_block('simulink/Sources/In1', [sys '/Rload'], ...
        'Position', [45 330 75 350]);

    add_block('simulink/Math Operations/Product', [sys '/Vin * duty'], ...
        'Position', [135 85 175 130], ...
        'Inputs', '**');
    add_block('simulink/Math Operations/Sum', [sys '/vL = VinD - Vout - iLr'], ...
        'Position', [270 115 310 175], ...
        'Inputs', '+--');
    add_block('simulink/Commonly Used Blocks/Gain', [sys '/1 over L 22uH'], ...
        'Position', [360 125 455 165], ...
        'Gain', '1/22e-6');
    add_block('simulink/Continuous/Integrator', [sys '/iL'], ...
        'Position', [505 125 555 165], ...
        'InitialCondition', '5');
    add_block('simulink/Commonly Used Blocks/Gain', [sys '/Rseries 0.02ohm'], ...
        'Position', [610 190 710 225], ...
        'Gain', '0.02');

    add_block('simulink/Math Operations/Product', [sys '/Iout = Vout div Rload'], ...
        'Position', [505 300 550 345], ...
        'Inputs', '*/');
    add_block('simulink/Math Operations/Sum', [sys '/iC = iL - Iout'], ...
        'Position', [610 270 650 320], ...
        'Inputs', '+-');
    add_block('simulink/Commonly Used Blocks/Gain', [sys '/1 over C 100uF'], ...
        'Position', [700 278 805 312], ...
        'Gain', '1/100e-6');
    add_block('simulink/Continuous/Integrator', [sys '/Vout'], ...
        'Position', [850 275 900 315], ...
        'InitialCondition', '12');

    add_block('simulink/Sinks/Out1', [sys '/Vout out'], ...
        'Position', [995 285 1025 305]);
    add_block('simulink/Sinks/Out1', [sys '/IL out'], ...
        'Position', [995 135 1025 155]);
    add_block('simulink/Sinks/Out1', [sys '/Iout out'], ...
        'Position', [995 360 1025 380]);

    add_line(sys, 'Vin/1', 'Vin * duty/1', 'autorouting', 'on');
    add_line(sys, 'duty/1', 'Vin * duty/2', 'autorouting', 'on');
    add_line(sys, 'Vin * duty/1', 'vL = VinD - Vout - iLr/1', 'autorouting', 'on');
    add_line(sys, 'vL = VinD - Vout - iLr/1', '1 over L 22uH/1', 'autorouting', 'on');
    add_line(sys, '1 over L 22uH/1', 'iL/1', 'autorouting', 'on');
    add_line(sys, 'iL/1', 'Rseries 0.02ohm/1', 'autorouting', 'on');
    add_line(sys, 'Rseries 0.02ohm/1', 'vL = VinD - Vout - iLr/3', 'autorouting', 'on');
    add_line(sys, 'iL/1', 'iC = iL - Iout/1', 'autorouting', 'on');
    add_line(sys, 'iL/1', 'IL out/1', 'autorouting', 'on');

    add_line(sys, 'Vout/1', 'vL = VinD - Vout - iLr/2', 'autorouting', 'on');
    add_line(sys, 'Vout/1', 'Iout = Vout div Rload/1', 'autorouting', 'on');
    add_line(sys, 'Rload/1', 'Iout = Vout div Rload/2', 'autorouting', 'on');
    add_line(sys, 'Iout = Vout div Rload/1', 'iC = iL - Iout/2', 'autorouting', 'on');
    add_line(sys, 'Iout = Vout div Rload/1', 'Iout out/1', 'autorouting', 'on');
    add_line(sys, 'iC = iL - Iout/1', '1 over C 100uF/1', 'autorouting', 'on');
    add_line(sys, '1 over C 100uF/1', 'Vout/1', 'autorouting', 'on');
    add_line(sys, 'Vout/1', 'Vout out/1', 'autorouting', 'on');

    Simulink.BlockDiagram.arrangeSystem(sys);
    close_system(sys);
end
